# Leonel Alejandro Torres Pérez.

name: Hello World con la herramienta workflow
on: 
  workflow_dispatch:
jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
    - name: Holaaaa
      run: echo "Hello World"
      
    - name: Fecha
      run: echo "El día de hoy es $(date +'%A, %d de %B de %Y')"

    - name: Actualizacion
      run: sudo apt update 

      
